version: '3'

services:
  db:
    image: mysql:5.7
    container_name: wordpressdb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./php.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db

  nodejs:
    build:
      context: ./wp-content/themes/coopers
      dockerfile: Dockerfile.nodejs
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - /var/www/html/wp-content/node_modules
    restart: "on-failure"
    depends_on:
      - wordpress

volumes:
  db_data: